### ISSUE TITLE
Create a .gitignore file

### ISSUE THREAD

**Issue by SHxKM** [ado120/alexander_blog#1]
Better to include in it the path to these, at the least:

- `settings.py` (contains the secret key)
- `db.sqlite3` (database)
- `.idea` (Pycharm IDE files)
- `.pyc` files (these can actually cause headache sometimes)

Good job!

**Comment by ado120** [comment]
Hmmm.. if I don't sync the database I have to recreate posts on another dev machine right?

**Comment by SHxKM** [comment]
> Hmmm.. if I don't sync the database I have to recreate posts on another dev machine right?

Correct.
